[#UPD] - Updated for the latest NFCPassportReader (commit: 89813ba);
TechTeamer/NFCPassportReader pull request #3
Opened 2024-09-20 07:32 UTC by jkirtyan-dev

2024-09-20 08:14 UTC, ayden89 commented
@jkirtyan-dev Nekem az NFCPassportReaderApp PassportView 57-es sora miatt nem fordul, hiányolja a konstruktor hívásból a parserConfig-ot.

2024-09-20 08:16 UTC, ayden89 requested changes
@jkirtyan-dev Nekem az NFCPassportReaderApp PassportView 57-es sora miatt nem fordul, hiányolja a konstruktor hívásból a parserConfig-ot.

2024-09-20 11:13 UTC, ayden89 approved these changes
LGTM

2024-09-25 09:38 UTC, fkombruha commented
találtam issuet, Jánossal már egyeztettem

2024-09-26 10:59 UTC, fkombruha approved these changes

2024-09-26 10:59 UTC, merged